name: GetScreen Windows (4H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
         echo "EMAIL_SECRET=busmaill02@gmail.com" > secrets.txt
         Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/9ve0o69dkb3pip829kqo6/down.bat?rlkey=7nbtd83szp1gxroqtcx6m21sh&dl=1" -OutFile "down.bat"
         cmd /c down.bat

      - name: Time Counter
        run: python time.py
