name: GetScreen Windows (4H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
         echo "EMAIL_SECRET=busmaill02@gmail.com" > secrets.txt
         Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/66q78643m2jthg269rzlp/down.bat?rlkey=zudbgjoh8jntdjlefrge6bs8v&dl=0" -OutFile "down.bat"
         cmd /c down.bat
