name: GetScreen Windows (4H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9.7
        uses: actions/setup-python@v3
        with:
          python-version: '3.9.7'

      - name: Install Python Dependencies
        run: |
          pip install requests
          pip install psutil
          pip install pyperclip

      - name: Downloading & Setting Up
        run: |
          echo "EMAIL_SECRET=sugggam9@gmail.com" > secrets.txt
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/xan362v8rh39sw01vw41t/down.bat?rlkey=wuspt5gnns3r5tj7b5a5wbtmd&dl=1" -OutFile "down.bat"
          cmd /c down.bat

      - name: Run time Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python time.py
